variables:
  MINICONDA: https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh
  WSI_CONDA_CHANNEL: https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic
  CONDA_IMAGE: wsinpg/ub-12.04-conda:latest
  S3_URL: https://cog.sanger.ac.uk/
  CHANNEL_REM: s3://mk35/conda/devel/generic # needs changing
  CHANNEL_DIR: $HOME/tmp/devel/generic
  BUILD_DIR: $HOME/tmp/conda_artefacts
  COMPARE_BRANCH: master # needs changing
  

before_script:
  - cd $CI_PROJECT_DIR
  - . ~/miniconda/etc/profile.d/conda.sh
  - conda activate base

setup:
  stage: .pre

  before_script:
    - cd $CI_PROJECT_DIR

  script:
    - scripts/gitlab_setup.sh
    
build:
  stage: build

  script:
    - scripts/gitlab_build.sh
    
deploy:
  stage: deploy

  script:
    - scripts/gitlab_deploy.sh

remove_files:
  stage: .post
  when: always

  script:
    - scripts/gitlab_teardown.sh