{% set version = "3.0.0.prerelease" %}
{% set irods_version = "4.2.7" %}

package:
  name: baton-pkg
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/baton
  license: GPL2
  summary: Client programs and API for use with iRODS (Integrated Rule-Oriented Data System).

build:
  number: 1

source:
  git_url: https://github.com/wtsi-npg/baton.git
  git_rev: ac3d2e7c461dd53dc6a541ec87de7a41aaa715d8

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - libtool
    - make
    - perl
    - pkg-config
  host:
    - irods-dev =={{ irods_version }}
    - irods-runtime =={{ irods_version }}
    - libjansson-dev
    - libssl-dev

outputs:
  - name: baton
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - libtool
        - make
        - perl
        - pkg-config
      host:
        - irods-dev =={{ irods_version }}
        - libjansson-dev
        - libssl-dev
      run:
        - {{ pin_subpackage("libbaton", exact=True) }}
        - irods-runtime =={{ irods_version }}
        - libjansson
        - libssl
    files:
      - bin/baton-*
    test:
      commands:
        - baton-list --version

  - name: libbaton
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - libtool
        - make
        - perl
        - pkg-config
      host:
        - irods-dev =={{ irods_version }}
        - libjansson-dev
        - libssl-dev
      run:
        - irods-runtime =={{ irods_version }}
        - libjansson
        - libssl
    files:
      - lib/libbaton.*
    test:
      commands:
        - test -h ${PREFIX}/lib/libbaton.so

  - name: libbaton-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libbaton", exact=True) }}
    files:
      - include/baton
      - lib/pkgconfig/baton.pc
    test:
      commands:
        - test -f ${PREFIX}/include/baton/baton.h
